CREATE TABLE PAIS(
	ID INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL,
);

CREATE TABLE CIDADE(
	ID INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL,
	NUMERO_HABITANTES INT NOT NULL,
	CURIOSIDADES VARCHAR(200) NOT NULL,
	PAISID INT FOREIGN KEY REFERENCES PAIS(ID)
);

select * from cidade


INSERT INTO PAIS (ID, NOME) VALUES (1,'Brasil')
INSERT INTO PAIS (ID, NOME) VALUES (2,'Portugal')

INSERT INTO CIDADE (ID,NOME,NUMERO_HABITANTES, CURIOSIDADES, PAISID) VALUES (1,'Goiânia','2','GOIANIA FAZ CALOR', 1)
INSERT INTO CIDADE (ID,NOME,NUMERO_HABITANTES, CURIOSIDADES, PAISID) VALUES (2,'São Paulo','3','Sampa', 1)
INSERT INTO CIDADE (ID,NOME,NUMERO_HABITANTES, CURIOSIDADES, PAISID) VALUES (3,'Lisboa','2','Lisboa é a capital de Portugal', 2)
INSERT INTO CIDADE (ID,NOME,NUMERO_HABITANTES, CURIOSIDADES, PAISID) VALUES (4,'Porto','3','Porto é uma cidade de Portugal', 2)

drop table pais
drop table cidade